### ISSUE TITLE
Could not find a part of the path Mods

### ISSUE THREAD

**Issue by WSP-webmaster** [Karlovsky120/7DaysProfileEditor#5] opened 2017-01-13 22:24 UTC
Time Stamp: 1/13/2017
Message: Could not find a part of the path 'L:\Steam\SteamApps\common\7 Days To Die\Mods'.
Source: mscorlib
Inner Exception: 
Stack Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path, String searchPattern)
   at SevenDaysProfileEditor.Data.IconData.ReadModdedItemIcons()
   at SevenDaysProfileEditor.Program.Initialize()
Target Site: Void WinIOError(Int32, System.String)

**Comment by Karlovsky120** [comment] 2017-01-13 22:53
I can't really do anything with just this.

What's the contex, what were you trying to do when the error occured?

Were you trying to create an error report?
If so, I think I know what's wrong.
As a temporary fix, create "Mods" folder in games root directory and it should work. I'll fix it properly when I'm able.

If this was not it, yeah, more context would be nice. :)

**Comment by NGD-Skier** [comment] 2017-01-13 23:32
Oh yeah, I think I had to do that too a while back.  It was weird. All I 
had to do was create the empty folder, and whatever error I was getting 
went away.

   -Mike

**Comment by Karlovsky120** [comment] 2017-01-14 23:18
It should be fixed now. Will close issue when confirmed.

**Comment by WSP-webmaster** [comment] 2017-01-15 21:29
It now opens with no issues and I can see icons in the invintory section where before they were blank but, after selecting the 7daystodie.exe the window does not close after hitting "open". Next time the program tries to run I get (in the black 7DaysProfileEditor.exe window)
Unhandled Exception: System.AaccessViolationException: Attempted to read or write protected memory.
at SevenDaysProfileEditor.Data.IconData.ReadDefaultItemIcons()
at SevenDaysProfileEditor.Program.Initialize()
at SevenDaysProfileEditor.Program.Start(MainWindow window)
at SevenDaysProfileEditor.Program.Mian()

![7daystodieprofileedittoolcrash](https://cloud.githubusercontent.com/assets/7007298/21966367/bbf2dab4-db3f-11e6-875f-7e1edd2d0d1b.jpg)

**Comment by WSP-webmaster** [comment] 2017-01-15 21:32
If i delete the 7DaysProfileEditor.config file and the ProfileEditor.log I can run the program and it does not crash out

**Comment by Karlovsky120** [comment] 2017-01-15 23:41
So it works now?

Were you running the game by any chance when using the program?

On 15 Jan 2017 10:32 pm, "WSP-webmaster" <notifications@github.com> wrote:

If i delete the 7DaysProfileEditor.config file and the ProfileEditor.log I
can run the program and it does not crash out

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Karlovsky120/7DaysProfileEditor/issues/5#issuecomment-272725429>,
or mute the thread

**Comment by WSP-webmaster** [comment] 2017-01-16 06:09
No I was not running the program when this new error happens.

**Comment by Karlovsky120** [comment] 2017-04-20 15:31
This seems to be an issue with .NET. I myself cannot run release versions of my program on my computer because some process I'm running seems to clash with .NET. This does not happen with debug versions, so these are the ones I'm putting in the download folder. As far as I know, there's nothing I can do to fix this.

**Closed by Karlovsky120** 2017-04-20 15:31 UTC
